### ISSUE TITLE
[FIX] 카트 바텀시트 Config Change가 일어날 경우 수정한 입력 값이 날라가는 버그

### ISSUE THREAD

**Issue by mdb1217** [woowa-techcamp-2022/android-banchan-10#158]
제곧내.. Config Change 발생시 값이 사라지는 것 같아요~

https://user-images.githubusercontent.com/70698151/186861939-9bbb15d9-bdcf-4046-b2cc-1052d51f599d.mp4

**Comment by DAEHYEONJO** [comment]
문제원인: 바텀시트 뷰모델의 카트정보 불러오는 함수가 바텀시트가 생성될때마다 호출됨
해결방법: 바텀시트 뷰모델의 init에서 1회 호출하는것으로 수정
